version: "3.7"
services:
  nginx:
    build: requirements/nginx/
    # Maps the host machine's ports to the container's ports.
    ports:
      - "443:443"
    # Exposes port 9000 to other services in the same Docker network.
    # This does not make the port accessible from the host machine.
    expose:
      - "9000"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: dtolmaco
      WORDPRESS_DB_PASSWORD: dantol2004
      WORDPRESS_DB_NAME: inceptiondb
    volumes:
      - wordpress-data:/var/www/html
    expose:
      - "9000"
      - "3306"
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/
    environment:
      MYSQL_DATABASE: inceptiondb
      MYSQL_PASSWORD: dantol2004
      MYSQL_USER: dtolmaco
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception

volumes:
  wordpress-data:
  mariadb-data:
networks:
  inception:
