version: "3.7"
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx
    # Maps the host machine's ports to the container's ports.
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: ${dbhost}
      WORDPRESS_DB_USER: ${user}
      WORDPRESS_DB_PASSWORD: ${password}
      WORDPRESS_DB_NAME: ${dbname}
    volumes:
      - wordpress-data:/var/www/html
    # Exposes port 9000 to other services in the same Docker network.
    # This does not make the port accessible from the host machine.
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb
    entrypoint: ["/dbsetup.sh"]
    environment:
      MYSQL_DATABASE: ${dbname}
      MYSQL_PASSWORD: ${password}
      MYSQL_USER: ${user}
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception

volumes:
  wordpress-data:
    name: wordpress-data
  mariadb-data:
    name: mariadb-data
networks:
  inception:
