version: "3.7"
services:
  nginx:
    build: nginx/
    # Maps the host machine's ports to the container's ports.
    ports:
      - "443:443"
    # Exposes port 9000 to other services in the same Docker network.
    # This does not make the port accessible from the host machine.
    expose:
      - "9000"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build: wordpress/
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: dantol2004
      WORDPRESS_DB_NAME: mysql
    volumes:
      - wordpress-data:/var/www/html
    expose:
      - "9000"
      - "3306"
    depends_on:
      - mariadb

  mariadb:
    build: mariadb/
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: dantol2004
      MYSQL_USER: root
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  wordpress-data:
  mariadb-data:
